language: java

sudo: required

jdk:
        - oraclejdk8
        - openjdk7

before_install:
        - cd java

install: true

script:
       - sudo apt-get update && sudo apt-get install oracle-java8-installer
       - sudo apt-get install openjdk-7-jdk

before_install:
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
